### ISSUE TITLE
HTTP URI not playing

### ISSUE THREAD

**Issue by mariusbloemhof** [finncodes/iptv#3]
Hi, I have an URL that does not play. I am loading the URL directly into the url property of ReactPlayer, but it is not playing.

I can open the same source URL from any other player - any ideas?

**Comment by finncodes** [comment]
Hello,

It sounds like your issue is related to the ReactPlayer library - posting on their [repo](https://github.com/CookPete/react-player) could help you find a solution quicker.

Have you checked your browser's console while trying to play the video? The most recent bug that I fixed was because of a mixed content error as the source URL wasn't served over HTTPS.
